Home work for lesson2.
IvanShadrin-97/geekshop pull request #2
Opened 2021-05-31 09:12 UTC by IvanShadrin-97

Тз вроде получилось выполнить, но сам понимаю что костыль сделал во вьюшке...( Но это с учётом того что на Камчатке отрубили всю связь на пол дня все провайдеры, даже по телефону ни куда позвонить не мог, пришлось путём перебора все через for пробывать даже к встроенной документации обращался, но так и не полуилось без костыля обойтись) Вообще задумка с img была в {% static path_var %}  такой пример был в встроенной документации. Но тоже не получилось реализовать циклом фор так как ccs даёт о себе знать и каждый элемент находится на своём месте. При проходу цикала  к примеру по первому товару всё выстраевается в колонку и т.д

2021-05-31 11:53 UTC, Vokler requested changes

2021-05-31 11:53 UTC, Vokler commented on products/views.py
> +        'product1':[{'img': '"vendor/img/products/Adidas-hoodie.png"',
Не совсем верно тут, скорее всего из-за и возникали ошибки.
В общем, нужно было организовать только один спсиок:
`{..., 'products': [{...}, {...}, {...}]}`. Как-то так
Сегодня на уроке еще разберем

2021-05-31 14:56 UTC, Vokler requested changes

2021-05-31 14:56 UTC, Vokler commented on products/views.py
> +    #     'product': [
То, что закомментировано - верно

2021-05-31 20:19 UTC, IvanShadrin-97 commented on products/views.py
> +    #     'product': [
Я это понимаю, реализивать не полуилось в самом product.html, сейчас посмотрю урок может понятней станет)

2021-05-31 22:46 UTC, IvanShadrin-97 commented on products/views.py
> +        'product1':[{'img': '"vendor/img/products/Adidas-hoodie.png"',
Сделал ещё 1 комит в данной ветке, можете посмотреть код? Данная реализация пришла в голову сразу, но в моём коде она не работает, не знаю почему никаких ошибок не выдаёт ничего не подсвечивает, просто не вдаёт на страницу products.html список продуктов.

2021-06-01 06:36 UTC, Vokler commented on products/views.py
> +        'product1':[{'img': '"vendor/img/products/Adidas-hoodie.png"',
У вас не работает, потому что вы ключ указали в context для списка продуктов `product`. А в products.html делаете иттерацию по `products`, хотя такого ключа нет

2021-06-01 06:47 UTC, IvanShadrin-97 commented on products/views.py
> +        'product1':[{'img': '"vendor/img/products/Adidas-hoodie.png"',
Ну даю два дня подряд... ошибку в одном и том же месте, всё заработало, сейчас 3ий комит сделаю в эту ветку.
Вчера видимо тоже в этом же месте ошибался...

2021-06-01 18:13 UTC, Vokler approved these changes

2021-06-01 18:13 UTC, merged