Lesson3
IvanShadrin-97/geekshop pull request #3
Opened 2021-06-03 07:58 UTC by IvanShadrin-97

Работает всё исправно, только немного голову поломал почему всё кроме изображений подгружается на старницу

2021-06-03 10:59 UTC, Vokler requested changes

2021-06-03 10:59 UTC, Vokler commented on products/views.py
> +    convert_to_list_dict.query = pickle.loads(pickle.dumps(products_from_sql.query))
А зачем вы конвентируете это все в таком образе?)
Так же добавьте категории в context и выведите их в products.html

2021-06-03 10:59 UTC, Vokler commented
Так же у вас есть конфликты (это когда код в отпачкованной ветке конфликтует с главной веткой) между двумя ветками. Чтобы решить данную проблему:
1. В текущей ветке сделайте git pull master ветки
2. А потом сделайте git push

2021-06-03 19:12 UTC, IvanShadrin-97 commented on products/views.py
> +    convert_to_list_dict.query = pickle.loads(pickle.dumps(products_from_sql.query))
Просто заёшл в джанго документацию и увидел способ ковертировть в формат [{key: value}], что-бы не переписывать в products.html что-то решил как-то так реализовать.

2021-06-03 19:12 UTC, IvanShadrin-97 commented on products/views.py
> +    convert_to_list_dict.query = pickle.loads(pickle.dumps(products_from_sql.query))
После работы сегодня уже добавлю категории

2021-06-04 07:54 UTC, Vokler commented on products/views.py
> +    convert_to_list_dict.query = pickle.loads(pickle.dumps(products_from_sql.query))
Не надо переводить, можно просто оставить Products.objects.all() и все будет тоже работать

2021-06-04 08:54 UTC, IvanShadrin-97 commented on products/views.py
> +    convert_to_list_dict.query = pickle.loads(pickle.dumps(products_from_sql.query))
Добавил категории в контроллер, передлал на просто Prdoucts.object.all(), на самом деле это была моя первая задумка так сделать в коде, но даже не пробывал сразу реализовать в коде, попробывал в консоле поигртаься с обектами из БД и на данный запрос получал реализацию метода str в продуктах. Зашёл в дажнго документацию и там сразу явное преобразвоание к [{}] формату) Как то так.

2021-06-04 09:20 UTC, Vokler approved these changes

2021-06-04 09:20 UTC, merged