Lesson6
IvanShadrin-97/geekshop pull request #6
Opened 2021-06-14 02:19 UTC by IvanShadrin-97

Не могу разобраться с ошибкой, в контролере закоментировал строку кода которая по идее правильная, но с ней вылетает ошибка при увеличение количества товаров. Без полного пути 'baskets/basket.html' ошибки нету но нужно перезагружать страницу что-бы отображение поменялось. Ломал голову пол дня ничего на ум не пришло, все пути все проврил...

2021-06-16 07:58 UTC, Vokler requested changes

2021-06-16 07:58 UTC, Vokler commented on static/js/basket.js
> +                    $('.basket-list').html(data.result)
У вас здесь ошибка, нужно `basket_list`, с нижним подчеркиванием

2021-06-16 08:24 UTC, IvanShadrin-97 commented on static/js/basket.js
> +                    $('.basket-list').html(data.result)
Исправил

2021-06-16 08:24 UTC, IvanShadrin-97 commented on static/js/basket.js
> +                    $('.basket-list').html(data.result)
Теперь работает

2021-06-17 08:47 UTC, Vokler approved these changes

2021-06-17 08:47 UTC, merged